apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-engine
  labels:
    app: recommendation-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-engine
  template:
    metadata:
      labels:
        app: recommendation-engine
    spec:
      containers:
        - name: api
          image: recommendation-engine:local
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /v1/readyz
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-engine
spec:
  selector:
    app: recommendation-engine
  ports:
    - port: 80
      targetPort: 8080
